### ISSUE TITLE
Compatible with Laravel 6?

### ISSUE THREAD

**Issue by 4n70w4** [greabock/tentacles#3]
Or advise another package compatible with Laravel 6?

**Comment by greabock** [comment]
Feel free to create PR.
Otherwise you have to wait day or two.

**Comment by 4n70w4** [comment]
I can not help because I have never used your package and I don’t know how it works and how to test all cases.

**Comment by 4n70w4** [comment]
I made a fix so that Macroable works with models https://github.com/laravel/framework/pull/31286

**Comment by greabock** [comment]
be happy!

https://github.com/laravel/framework/pull/33025
